"""
Schema Crawler Tool - Converts JSON Schema to Zod + TypeScript

This tool integrates the schema-crawler.ts functionality into the Python agent,
allowing runtime conversion of JSON Schemas to Zod validation schemas.
"""

from google.adk.tools import ToolContext
from typing import Dict, Any, Optional
import json
import subprocess
import os
from pathlib import Path

# Path to schema-crawler.ts
SCHEMA_CRAWLER_PATH = Path(__file__).parent.parent.parent / "agent-generator" / "src" / "mcp-registry" / "schema-crawler.ts"

def generate_zod_from_json_schema(
    tool_context: ToolContext,
    json_schema: Dict[str, Any],
    schema_name: str,
    output_path: Optional[str] = None
) -> Dict[str, str]:
    """
    Convert JSON Schema to Zod validation schema + TypeScript types.
    
    Args:
        json_schema: JSON Schema object to convert
        schema_name: Name for the generated schema (e.g., "PersonInput")
        output_path: Optional path to write generated module (if None, returns code as string)
    
    Returns:
        Dictionary with:
        - status: "success" or "error"
        - zod_code: Generated Zod schema code
        - type_definition: Generated TypeScript interface
        - validator_code: Generated validation functions
        - file_path: Path where module was written (if output_path provided)
    """
    try:
        # Validate inputs
        if not isinstance(json_schema, dict):
            return {
                "status": "error",
                "message": "json_schema must be a dictionary"
            }
        
        if not schema_name or not isinstance(schema_name, str):
            return {
                "status": "error",
                "message": "schema_name must be a non-empty string"
            }
        
        # Create temporary input file
        import tempfile
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as tmp:
            json.dump({
                "schema": json_schema,
                "name": schema_name
            }, tmp)
            tmp_path = tmp.name
        
        try:
            # Call Node.js script to run schema-crawler
            result = subprocess.run(
                ['node', '-e', f'''
const {{ generateZodFromJSONSchema }} = require("{SCHEMA_CRAWLER_PATH}");
const fs = require("fs");
const input = JSON.parse(fs.readFileSync("{tmp_path}", "utf-8"));
const output = generateZodFromJSONSchema(input.schema, input.name);
console.log(JSON.stringify(output));
                '''],
                capture_output=True,
                text=True,
                timeout=30
            )
            
            if result.returncode != 0:
                return {
                    "status": "error",
                    "message": f"Schema generation failed: {result.stderr}"
                }
            
            # Parse output
            output = json.loads(result.stdout)
            
            # Write to file if output_path provided
            if output_path:
                output_file = Path(output_path)
                output_file.parent.mkdir(parents=True, exist_ok=True)
                
                module_code = f'''/**
 * Auto-generated by schema-crawler tool
 * Schema: {schema_name}
 * Generated: {import_datetime()}
 */

import {{ z }} from 'zod';

/* ==================== TYPE DEFINITION ==================== */

{output["typeDefinition"]}

/* ==================== ZOD SCHEMA ==================== */

export const {schema_name}Schema = {output["zodCode"]};

/* ==================== VALIDATORS ==================== */

{output["validatorCode"]}
'''
                
                output_file.write_text(module_code)
                
                return {
                    "status": "success",
                    "zod_code": output["zodCode"],
                    "type_definition": output["typeDefinition"],
                    "validator_code": output["validatorCode"],
                    "file_path": str(output_file),
                    "message": f"Schema generated and written to {output_file}"
                }
            
            # Return code as strings
            return {
                "status": "success",
                "zod_code": output["zodCode"],
                "type_definition": output["typeDefinition"],
                "validator_code": output["validatorCode"],
                "message": f"Schema '{schema_name}' generated successfully"
            }
        
        finally:
            # Clean up temp file
            os.unlink(tmp_path)
    
    except subprocess.TimeoutExpired:
        return {
            "status": "error",
            "message": "Schema generation timed out (>30s)"
        }
    except Exception as e:
        return {
            "status": "error",
            "message": f"Unexpected error: {str(e)}"
        }

def generate_zod_module(
    tool_context: ToolContext,
    tool_name: str,
    input_schema: Dict[str, Any],
    output_schema: Optional[Dict[str, Any]] = None,
    output_path: Optional[str] = None
) -> Dict[str, str]:
    """
    Generate complete TypeScript module with Zod schemas for tool input/output.
    
    Args:
        tool_name: Name of the tool (e.g., "getWeather")
        input_schema: JSON Schema for tool input
        output_schema: Optional JSON Schema for tool output
        output_path: Optional path to write module file
    
    Returns:
        Dictionary with:
        - status: "success" or "error"
        - module_code: Complete TypeScript module
        - file_path: Path where module was written (if output_path provided)
    """
    try:
        # Generate input schema
        input_result = generate_zod_from_json_schema(
            tool_context,
            input_schema,
            f"{tool_name}Input"
        )
        
        if input_result["status"] != "success":
            return input_result
        
        # Generate output schema if provided
        output_result = None
        if output_schema:
            output_result = generate_zod_from_json_schema(
                tool_context,
                output_schema,
                f"{tool_name}Output"
            )
            
            if output_result["status"] != "success":
                return output_result
        
        # Construct complete module
        module_code = f'''/**
 * Auto-generated by schema-crawler tool
 * MCP Tool: {tool_name}
 * Generated: {import_datetime()}
 */

import {{ z }} from 'zod';

/* ==================== INPUT ==================== */

{input_result["type_definition"]}

export const {tool_name}InputSchema = {input_result["zod_code"]};

{input_result["validator_code"]}

{f"""/* ==================== OUTPUT ==================== */

{output_result["type_definition"]}

export const {tool_name}OutputSchema = {output_result["zod_code"]};

{output_result["validator_code"]}""" if output_result else ""}

/* ==================== TOOL DEFINITION ==================== */

export const {tool_name}Tool = {{
  name: '{tool_name}',
  inputSchema: {tool_name}InputSchema,
  {f"outputSchema: {tool_name}OutputSchema," if output_result else "outputSchema: z.unknown(),"}
}} as const;
'''
        
        # Write to file if output_path provided
        if output_path:
            output_file = Path(output_path)
            output_file.parent.mkdir(parents=True, exist_ok=True)
            output_file.write_text(module_code)
            
            return {
                "status": "success",
                "module_code": module_code,
                "file_path": str(output_file),
                "message": f"Module for {tool_name} generated and written to {output_file}"
            }
        
        return {
            "status": "success",
            "module_code": module_code,
            "message": f"Module for {tool_name} generated successfully"
        }
    
    except Exception as e:
        return {
            "status": "error",
            "message": f"Module generation failed: {str(e)}"
        }

def import_datetime():
    """Helper to import datetime"""
    from datetime import datetime
    return datetime.utcnow().isoformat()

# Tool metadata for registration
TOOL_METADATA = {
    "generate_zod_from_json_schema": {
        "description": "Convert JSON Schema to Zod validation schema with TypeScript types",
        "parameters": {
            "json_schema": "dict",
            "schema_name": "str",
            "output_path": "Optional[str]"
        }
    },
    "generate_zod_module": {
        "description": "Generate complete Zod module for MCP tool with input/output schemas",
        "parameters": {
            "tool_name": "str",
            "input_schema": "dict",
            "output_schema": "Optional[dict]",
            "output_path": "Optional[str]"
        }
    }
}
